FROM registry.gitlab.com/pal-robotics/tg010123/dockers/pal-gallium-pal-metapkg-development-tiago-218-dev:latest
ENTRYPOINT [ ]
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
 && apt-get install -y --no-install-recommends ros-noetic-moveit

SHELL ["/bin/bash", "-c"]
RUN source /opt/pal/gallium/setup.bash
RUN echo "source /opt/pal/gallium/setup.bash" >> ~/.bashrc
RUN source ~/.bashrc

WORKDIR /root


